version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub