---
- name: enabling opcache cli
  lineinfile:
    dest: /etc/php/7.0/cli/php.ini
    regexp: ';?opcache.enable=\d'
    line: 'opcache.enable=1'

- name: ensure timezone is set in cli php.ini
  lineinfile:
    dest: /etc/php/7.0/cli/php.ini
    regexp: 'date.timezone ='
    line: 'date.timezone = {{ server.timezone }}'